language: python
python: 3.4
addons:
  postgresql: "9.4"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip
  - pip install coveralls -r requirements.txt -r requirements-dev.txt
  - git clone https://github.com/City-of-Helsinki/respa.git _respa
  - (cd _respa && git checkout ee680c34674cc)
  - pip install -r _respa/requirements.txt
  - pip install -e ./_respa
script:
  - psql template1 -c 'create extension hstore;'
  - py.test -vvv --cov respa_exchange respa_exchange
after_success:
  - coveralls
